version: 0.1

phases:
  install:
    commands:
      - echo Installing Bundler...
      - gem install bundler
      - bundle install --with test
      - echo Installing Nodejs...
      - sudo apt install curl
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
      - sudo apt-get install nodejs
      - echo Installing PostgreSQL...
      - sudo su -
      - apt-get install postgresql postgresql-contrib
      - apt-get install postgresql postgresql-contrib
      - service postgresql start
  pre_build:
    commands:
      - echo Preparing database...
      # - cp config/database.yml.example config/database.yml
      - bundle exec rake db:setup
  build:
    commands:
      # - echo Running rspec tests...
      # - bundle exec rspec spec/
