version: 0.1

phases:
  install:
    commands:
      - echo Starting postgresql...
      - service postgresql restart
      - echo Installing Bundler...
      - gem install bundler
      - bundle install
  pre_build:
    commands:
      - echo Preparing database to run tests...
      - cp config/database.yml.example config/database.yml
      - bundle exec rake db:setup
      - bundle exec rake db:migrate
      - bundle exec rake db:seed
  build:
    commands:
      # - echo Running rspec tests...
      # - bundle exec rspec spec/
